# This is a basic workflow to help you get started with Actions
name: CI

on: 
  :push
     branches:
       -master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Select platform(s)
        os: [ ubuntu-latest, macos-latest ]
        # Select compatible Smalltalk image(s)
        smalltalk: [ Squeak64-trunk, Squeak64-5.3, Squeak64-5.2 ]
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - run: echo "::set-env name=RELEASE_TITLE::$( date +%d.%m.%y_%H_%M_%s )"
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15
